name: lotus-fvm-localnet-lite

on:
  push:
    paths:
      - .github/workflows/container-lite.yml
      - Dockerfile-lite
  repository_dispatch:
    types: [manual-run-lite]
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-lite

jobs:
  run-build-and-push-oci-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    outputs:
      digest: ${{ steps.fetch_digest.outputs.digest }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: Dockerfile-lite
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Dockerfile-python
        run: |
          echo Digest: ${{ steps.build.outputs.digest }}
          perl -pi -e "s#^FROM .*#FROM ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}\@${{ steps.build.outputs.digest }}" Dockerfile-python

      - name: Commit and push changes to Dockerfile-python
        run: |
          set -euo pipefail
          set -x
          git config --global user.name 'update-image-hash'
          git config --global user.email 'nobody@jimpick.com'
          git status
          git add Dockerfile-python
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m 'Update lotus-fvm-localnet-lite from action'
            git pull
            git push
          fi

      - name: Trigger -python build
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"manual-run-python"}'
