name: lotus-fvm-localnet

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: jimpick/lotus-fvm-localnet

jobs:
  run-build-and-push-oci-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.fetch_digest.outputs.digest }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build_and_push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Fetch digest
        id: fetch_digest
        run: |
          # https://github.community/t/how-to-check-if-a-container-image-exists-on-ghcr/154836
          TOKEN=$(curl -s https://ghcr.io/token\?scope\="repository:jimpick/lotus-fvm-localnet:pull" | jq -r .token)
          # curl -I -H "Authorization: Bearer $TOKEN" https://ghcr.io/v2/jimpick/lotus-fvm-localnet/manifests/main
          DIGEST=$(curl -s -I -H "Authorization: Bearer $TOKEN" https://ghcr.io/v2/jimpick/lotus-fvm-localnet/manifests/main | sed -n 's/^docker-content-digest: //p')
          echo $DIGEST
          echo "::set-output name=digest::$DIGEST"

      - name: Outputs
        run: |
          echo digest: ${{ steps.fetch_digest.outputs.digest }}

